services:
  # Backend Express API
  - type: web
    name: wordmap-zeitgeist-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SCRAPE_SECRET
        generateValue: true
    healthCheckPath: /health

  # Frontend Static Site
  - type: static
    name: wordmap-zeitgeist-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /api/*
        destination: https://wordmap-zeitgeist-backend.onrender.com$1
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff