name: Update Supabase Types

on:
  # Allow manual trigger when needed
  workflow_dispatch:
  
  # Run when migrations are added or modified
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/update-supabase-types.yml'
  
  # Run on PRs that modify migrations (to catch issues early)
  pull_request:
    paths:
      - 'supabase/migrations/**'
  
  # Run after successful deployments to production
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
    branches: [main]

jobs:
  update-types:
    runs-on: ubuntu-latest
    # Skip if it's a workflow_run trigger from a failed deployment
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci
      
      - name: Generate Supabase types
        env:
          SUPABASE_PROJECT_ID: unqqozhwbyvukotkukpf
        run: |
          cd backend
          npx supabase gen types typescript --project-id "$SUPABASE_PROJECT_ID" > src/types/database.types.ts
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain backend/src/types/database.types.ts) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "### 🔄 Type changes detected" >> $GITHUB_STEP_SUMMARY
            echo "Database schema has changed and types need to be updated." >> $GITHUB_STEP_SUMMARY
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "### ✅ No type changes needed" >> $GITHUB_STEP_SUMMARY
            echo "Database types are already up to date." >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Supabase database types'
          title: '🤖 Update Supabase Database Types'
          body: |
            ## 🔄 Automated Type Update
            
            This PR updates the TypeScript types generated from the Supabase database schema.
            
            ### Trigger
            - **Event**: ${{ github.event_name }}
            - **Branch**: ${{ github.ref_name }}
            ${{ github.event_name == 'workflow_run' && format('- **After deployment**: {0}', github.event.workflow_run.name) || '' }}
            
            ### Generated Command
            ```bash
            npx supabase gen types typescript --project-id unqqozhwbyvukotkukpf
            ```
            
            ### Next Steps
            1. Review the type changes in `backend/src/types/database.types.ts`
            2. Ensure they match your expected schema modifications
            3. Run `npm run type-check` locally to verify no breaking changes
            4. Merge when ready
            
            ---
            *This PR was automatically created by the update-supabase-types workflow*
          branch: update-supabase-types
          delete-branch: true
          labels: |
            automated
            types
            supabase
          reviewers: kevinnorth
      
      - name: Comment on PR
        if: steps.check_changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Database Type Changes Detected**\n\nThis PR modifies database migrations. After merging, the Supabase types will be automatically updated in a follow-up PR.'
            })